apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: disturbing-swan-nodejs 
  janus-idp.io/tekton: disturbing-swan-nodejs
  backstage.io/kubernetes-id: disturbing-swan-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: disturbing-swan-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  