apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: disturbing-swan-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disturbing-swan-nodejs 
  name: disturbing-swan-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: disturbing-swan-nodejs 
